### ISSUE TITLE
Failed to compile: Module not found: Can't resolve 'containers/Home/Loadable'

### ISSUE THREAD

**Issue by sheluchin** [kangarang/tcr-ui#102]
```
Failed to compile

./src/App.js
Module not found: Can't resolve 'containers/Home/Loadable' in '/home/foo/repos/tcr-ui/src'

This error occurred during the build time and cannot be dismissed.
```

I get the above message in my browser after running:
```
  $ git clone https://github.com/kangarang/tcr-ui.git
  $ cd tcr-ui
  $ npm install
  $ npm run dev
```

**Comment by kangarang** [comment]
hrm, which node and browser version are you using?

**Comment by sheluchin** [comment]
```
$ npm --version
6.0.1

$ node --version
v8.11.1

$ firefox --version
Mozilla Firefox 61.0.1
```

**Comment by kangarang** [comment]
it is working on my machine with those versions

are you using any special terminal emulator? perhaps it's a path issue. try changing the import statement in `App.js` to import the module using a relative path. if you get a different error message, my intuition tells me that `/.env` is being ignored, and those environment variables are not being used to resolve absolute path imports
