### ISSUE TITLE
Apply called with wrong number of arguments

### ISSUE THREAD

**Issue by xwvvvvwx** [kangarang/tcr-ui#107]
`apply` is called with four arguments ([here](https://github.com/kangarang/tcr-ui/blob/master/src/modules/transactions/sagas/index.js#L82)), but the contract expects three arguments ([here](https://github.com/skmgoldin/tcr/blob/master/contracts/Registry.sol#L84)).

This meant that all calls to `apply` would fail for the TCR that I deployed.

If I remove the `listingID` argument from the call to apply and update the contract ABI's to match (e.g. [0xafbbefb788e478d30f2aca7c8fc8b8271a9603a2](ipfs.io/ipfs/0xafbbefb788e478d30f2aca7c8fc8b8271a9603a2)), then the calls to `apply` succeed (see [this commit](https://github.com/humansTCR/tcr-ui/commit/da484c6ff39c5e03cf923a2374dd14f87e4f9695))

Is this UI repo designed to work against an older version of the contracts? Am I missing something? I'm totally happy to submit a PR fixing this, if it is indeed a bug 🙂

**Comment by kangarang** [comment]
ah, just saw more of that commit: https://github.com/humansTCR/tcr-ui/commit/da484c6ff39c5e03cf923a2374dd14f87e4f9695. looks good to me!

**Comment by xwvvvvwx** [comment]
OK clear. Thanks for the detailed answer!
