### ISSUE TITLE
Couldn't run with ganache-cli

### ISSUE THREAD

**Issue by hailq** [kangarang/tcr-ui#79]
i get this issue when trying running with ganache-cli
```
registry saga err TypeError: Cannot read property 'address' of undefined
    at registrySaga$ (contracts.js:47)
```

It seems that it couldn't select the address cause there is no network_id of ganache in `abis.registry.networks[networkID]`

**Comment by kangarang** [comment]
hello, glad you were able to get it running at least.

have you deployed the contracts to local rpc (ganache-cli)? if you want to develop with ganache-cli, during the deployment, there's a few config stuff that you should modify for this project. specifically, the tokenHolders in the distribution of this file: https://github.com/skmgoldin/tcr/blob/master/conf/config.json

lemme know if you need help setting that up. it's just an edit of addresses and cli flags when starting up the rpc.

**Comment by kangarang** [comment]
otherwise, point your metamask to rinkeby or mainnet, and you should be able to see two registries that are deployed right now on those networks

**Comment by hailq** [comment]
My account has tokens, but it keeps send the failed transaction. You can see the following screenshots:

<img width="1414" alt="screen shot 2018-05-09 at 10 32 18 pm" src="https://user-images.githubusercontent.com/4117363/39824244-10d21884-53d9-11e8-868b-39cbc27a704a.png">

<img width="519" alt="screen shot 2018-05-09 at 10 32 31 pm" src="https://user-images.githubusercontent.com/4117363/39824252-16860114-53d9-11e8-9f25-76d99dc41074.png">

<img width="1410" alt="screen shot 2018-05-09 at 10 32 57 pm" src="https://user-images.githubusercontent.com/4117363/39824254-18929b98-53d9-11e8-804a-58ae7e5cec56.png">

**Comment by kangarang** [comment]
should be fixed with the latest push. sorry about that, there was a bug in the conditional statement in the Apply component: https://github.com/kangarang/tcr-ui/blob/master/src/views/containers/Transactions/Apply.js#L54

**Comment by kangarang** [comment]
with that, you'll be able to specify the token amount for approval

**Comment by hailq** [comment]
Don't know why, still couldn't do the registry approval

<img width="1410" alt="screen shot 2018-05-09 at 10 55 01 pm" src="https://user-images.githubusercontent.com/4117363/39825506-2261f3c8-53dc-11e8-8429-1a7aa2a0246c.png">

**Comment by kangarang** [comment]
is redux-logger printing any other errors before? e.g. on the setup part of the app?

**Comment by kangarang** [comment]
it's interesting that it says the minDeposit is 0 TEST, when it should be higher

**Comment by kangarang** [comment]
it gets the `minDeposit` from [here](https://github.com/kangarang/tcr-ui/blob/master/src/redux/modules/ethProvider/sagas/contracts.js#L132), where it queries the parameterizer contract and converts it based on the decimals of the token. not sure why it would return 0. to me, that seems like an issue that occurred during deployment pipeline. what was your config for token distribution?

**Comment by kangarang** [comment]
interesting. not thinking too deeply into it, try changing minDeposit to this: `"minDeposit": 10000000000000000000` (add 18 zeros to account for the token's `decimals`) and see if that makes a difference

**Comment by kangarang** [comment]
of course, you'll need to restart ganache and redeploy

**Comment by hailq** [comment]
The min deposit is changed, however the transaction is still failed :(
<img width="1417" alt="screen shot 2018-05-09 at 11 47 51 pm" src="https://user-images.githubusercontent.com/4117363/39827888-7f5e925a-53e3-11e8-9805-eaba6471085e.png">

**Comment by hailq** [comment]
Did it work on your ganache? Could you share me your configuration ?

**Comment by hailq** [comment]
it's weird it get error when trying to run with ganache-cli, however it works with `truffle develop` (on port 9545)

**Comment by kangarang** [comment]
my config is similar, and i don't believe it's the real cause of the problem. here it is for reference:

```
{
  "paramDefaults": {
    "minDeposit": 100000000000000000000,
    "pMinDeposit": 1000000000000000000000,
    "applyStageLength": 300,
    "pApplyStageLength": 86400,
    "commitStageLength": 600,
    "pCommitStageLength": 86400,
    "revealStageLength": 600,
    "pRevealStageLength": 86400,
    "dispensationPct": 50,
    "pDispensationPct": 50,
    "voteQuorum": 50,
    "pVoteQuorum": 50
	},
  "name": "TCR Factory",
  "token": {
    "address": "0x337cDDa6D41A327c5ad456166CCB781a9722AFf9",
    "deployToken": true,
    "decimals": "18",
    "name": "TrueToken",
    "symbol": "FACT",
    "supply": "1000000000000000000000000000",
    "tokenHolders": [
      { "address": "0xD09cc3Bc67E4294c4A446d8e4a2934a921410eD7",
        "amount": "1000000000000000000000000000" }
    ]
  }
}
```

any luck since 5 days ago??

**Comment by hailq** [comment]
Don't know why but it didn't seem to work with my ganache-cli. I had to deploy it to testnet. By the way, you also should print out the address of the deployed token to the console for using it later

**Comment by kangarang** [comment]
hm, that is curious. yes, you're right, for a better dev experience, i'll implement that (printing some top-level addresses). currently it's implemented in redux-logger; however it takes a few extra clicks. thank you for the suggestion.

**Comment by hailq** [comment]
It seems no hope of running with ganache gui . It failed all the time :( . Is there any way to debug it. I even can't approve the tokens for registry.

**Comment by kangarang** [comment]
try adding the mnemonic flag to ganache-cli: `--mnemonic "your mnemonic phrase here"`

**Comment by kangarang** [comment]
what does your `truffle.js` look like?

**Comment by hailq** [comment]
Here is my `truffle.js`:
```
const HDWalletProvider = require('truffle-hdwallet-provider')
const fs = require('fs')

let secrets
let mnemonic = ''

if (fs.existsSync('secrets.json')) {
  secrets = JSON.parse(fs.readFileSync('secrets.json', 'utf8'));
  ({mnemonic} = secrets)
}

module.exports = {
  networks: {
    mainnet: {
      provider: new HDWalletProvider(mnemonic, 'https://mainnet.infura.io'),
      network_id: '1',
      gas: 4500000,
      gasPrice: 10000000000,
    },
    rinkeby: {
      provider: new HDWalletProvider(mnemonic, 'https://rinkeby.infura.io'),
      network_id: '*',
      gas: 4500000,
      gasPrice: 25000000000,
    },
    ropsten: {
      provider: new HDWalletProvider(mnemonic, 'https://ropsten.infura.io'),
      network_id: '*',
      gas: 4500000,
      gasPrice: 25000000000,
    },
    ganache: {
      host: '127.0.0.1',
      port: 7545,
      network_id: '*',
      gas: 4500000,
      gasPrice: 25000000000,
    },
    dev: {
      host: '127.0.0.1',
      port: 8545,
      network_id: '*',
      gas: 4500000,
      gasPrice: 25000000000,
    },
    // config for solidity-coverage
    coverage: {
      host: 'localhost',
      network_id: '*',
      port: 7545, // <-- If you change this, also set the port option in .solcover.js.
      gas: 0xfffffffffff, // <-- Use this high gas value
      gasPrice: 0x01, // <-- Use this low gas price
    },
  },
}
```
i run the following commands: `npm run compile` -> `truffle migrate --network ganache` then add the registry address directly to `contract.js` file

**Comment by kangarang** [comment]
a ha! there's your problem. ganache-cli runs on port 8545

here's the truffle.js i use: https://github.com/kangarang/tcr/blob/master/truffle.js

make a mnemonic environment variable and use that same mnemonic to run ganache-cli with the flag `--mnemonic`

**Comment by hailq** [comment]
Actually i tried with the ganache gui which runs on port 7545: http://truffleframework.com/ganache/ . Could you try with that one ? It seems to be successful in migrating the contracts, however when it failed right from the "approve tokens for registry" step :(

**Comment by kangarang** [comment]
ah, it must be due to this line then: https://github.com/kangarang/tcr-ui/blob/master/src/redux/libs/provider.js#L40. change that to 7545

**Comment by hailq** [comment]
I though if i use metamask, it won't go to that line of code ?

**Comment by kangarang** [comment]
oh actually sorry, you are correct. is your metamask pointed at 7545?

**Comment by hailq** [comment]
yes, the website can show my balance (eth + my tokens) so it seems to be connected correctly.

**Comment by kangarang** [comment]
got anything else that can help me debug your error?

**Comment by hailq** [comment]
don't know why but it even fail when i trying running console to ganache gui
```
truffle(ganache)> registryInstance.apply(listHash, 10, "leuleu", {from: web3.eth.accounts[0], gas:450000})
Error: VM Exception while processing transaction: revert
    at SolidityFunction.execute (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
    at SolidityFunction.sendTransaction (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:170:1)
    at Eth.send [as sendTransaction] (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:145:1)
    at RequestManager.send (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:61:1)
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)

```

**Comment by kangarang** [comment]
so actually if you are directly invoking `instance.apply`, you need to convert the 2nd argument to account for the number of decimals your tokens specifies (likely 18, so add 18 zeros). and of course, `token.approve(registry_address, num_tokens)` beforehand.

could you post some expanded error logs you see in the browser please?

**Comment by kangarang** [comment]
hey @hailq, any luck? i just updated the docs, hope it's helpful. also left some clues for the [workaround](https://github.com/kangarang/tcr-ui#application-binary-interfaces) which you helped discover -- thanks for the feedback

**Comment by hailq** [comment]
👍
