### ISSUE TITLE
Cannot commit a vote

### ISSUE THREAD

**Issue by hailq** [kangarang/tcr-ui#80]
I get this issue with BN.js when trying to commit a new vote `commit vote saga error Error: [number-to-bn] while converting number false to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported.`

<img width="1430" alt="screen shot 2018-05-10 at 1 10 33 am" src="https://user-images.githubusercontent.com/4117363/39831542-0cec4a1c-53ef-11e8-9e75-c6bbeee52bf3.png">

**Comment by kangarang** [comment]
I'm almost positive that this is due to an error in https://github.com/kangarang/tcr-ui/commit/da0172024bba9e305b4e50941244dbe7fe22808a

**Comment by kangarang** [comment]
please pull the newest commit and lemme know if you're still getting any errors!

**Comment by kangarang** [comment]
related: https://app.zenhub.com/workspace/o/kangarang/tcr-ui/issues/83
