### ISSUE TITLE
Cann't reveal vote

### ISSUE THREAD

**Issue by hailq** [kangarang/tcr-ui#82]
I deployed the contract to rinkeby network, however i stuck at revealing the vote, it's failed all the time.

**Comment by kangarang** [comment]
hi, are you still having trouble revealing votes? if not, please post a screenshot or paste some error messages so i can help you out! thanks

**Comment by hailq** [comment]
Still cannot do the vote reveal
<img width="1438" alt="screen shot 2018-05-16 at 11 12 22 am" src="https://user-images.githubusercontent.com/4117363/40096220-216a7184-58fa-11e8-92a9-2418e69c6ec5.png">

**Comment by kangarang** [comment]
related: https://app.zenhub.com/workspace/o/kangarang/tcr-ui/issues/83
