### ISSUE TITLE
Couldn't request the voting rights

### ISSUE THREAD

**Issue by hailq** [kangarang/tcr-ui#83]
I try to request voting rights by got failed transaction
<img width="1410" alt="screen shot 2018-05-16 at 11 51 20 am" src="https://user-images.githubusercontent.com/4117363/40097298-94d818ce-58ff-11e8-9ea0-9f381230a75f.png">

**Comment by kangarang** [comment]
I think this is due to a bug that was introduced recently while i was adding styles to the commitVote container. i'm gonna push some changes right now. lemme know if you still have an issue after

**Comment by hailq** [comment]
It works perfectly now!

**Comment by kangarang** [comment]
awesome, glad it's working now. closing this, but feel free to keep opening issues and asking questions. this project needs a lot of work and im grateful for feedback
