### ISSUE TITLE
Couldn't do the vote

### ISSUE THREAD

**Issue by hailq** [kangarang/tcr-ui#84]
I don't know why but i got failed transaction when trying to do the voting
<img width="1434" alt="screen shot 2018-05-16 at 11 55 40 am" src="https://user-images.githubusercontent.com/4117363/40097397-20fb1b80-5900-11e8-94f2-92ca1ae7e1cb.png">

**Comment by kangarang** [comment]
this must be so frustrating for you! i'm sorry the app isn't playing nice.

could i see some more of the logs you get from the console? a screenshot of the logs that get printed after the listings/SET_LISTINGS action would be super helpful. like this:

<img width="554" alt="ss- 2018-05-16 at 1 26 40 am" src="https://user-images.githubusercontent.com/18040654/40098195-3949149c-58a8-11e8-95a3-e43225197762.png">

thanks

**Comment by kangarang** [comment]
another thing that just came to mind:

i think there's a bug [here](https://github.com/kangarang/tcr-ui/blob/master/src/redux/modules/transactions/sagas/index.js#L113) where ethjs doesn't actually receive the tx receipt. try adding a `yield call(delay, 1000)` on line 112 and see if that helps.

**Comment by hailq** [comment]
How to get SET_LISTING event ?

**Comment by hailq** [comment]
![screen shot 2018-05-16 at 12 36 32 pm](https://user-images.githubusercontent.com/4117363/40098484-dc68478a-5905-11e8-9917-15a5567f158c.png)

![screen shot 2018-05-16 at 12 36 58 pm](https://user-images.githubusercontent.com/4117363/40098489-e1778aba-5905-11e8-87b4-bc4b84d2a956.png)

**Comment by hailq** [comment]
Oh i got this error ` 'delay' is not defined  no-undef` , it seems that 'delay' wasn't declared.

**Comment by kangarang** [comment]
yes, please make sure to declare `delay` up at the top, where you import the `redux-saga/effects`

**Comment by hailq** [comment]
what is the content of delay function ?

**Comment by hailq** [comment]
did you mean import 'delay' from `redux-saga/effects`. I did this `import { select, put, call, fork, takeEvery, delay } from 'redux-saga/effects'` and got this error `'redux-saga/effects' does not contain an export named 'delay'.`

**Comment by hailq** [comment]
I put the delay `const delay = (ms) => new Promise(res => setTimeout(res, ms))`. But the transaction is still failed

**Comment by kangarang** [comment]
oooo, try importing `delay` from `redux-saga`, not `redux-saga/effects`. sorry for the misguidance

**Comment by hailq** [comment]
Still not working :(

**Comment by hailq** [comment]
Could you try it ? I deployed to Rinkeby testnet. Here is my token address: `0x97b4c6b720641fad64fb4a81f583289846e94192`, registry address: `0x225f49b7bfc88703c9c5f2f6c13c5a341461dd5f`. Send me your addresses then i will send you some tokens.

**Comment by kangarang** [comment]
related: https://app.zenhub.com/workspace/o/kangarang/tcr-ui/issues/83
