### ISSUE TITLE
Deposit token at starting application doesn't work?

### ISSUE THREAD

**Issue by hailq** [kangarang/tcr-ui#94]
I don't know the meaning of the deposit token when creating a new application, cause even i set a big amount of it it seems to be no difference in the next stages. I thought those tokens is used to limit the challengers as described here https://camo.githubusercontent.com/f16e12e98f8f8c5d79e7318bff1889b2c78363b9/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f656c61737469636265616e7374616c6b2d75732d656173742d312d3136373631313735323837342f64657461696c65642d776f726b666c6f772e706e67.
Sorry if i misunderstand something here.

**Comment by hailq** [comment]
I meant what is the difference when i start an application with 10 deposit token and 100 deposit token, cause it seems to be no difference to me

**Comment by kangarang** [comment]
if you deposit with 10, and the `minDeposit` changes to 11, your application will be at risk to be "touch-and-removed" - if someone calls `challenge` on that application, it's immediately removed without going to voting. see link above for more info.

**Comment by hailq** [comment]
oh, so the deposit at starting application stage only to deal with "touch-and-removed". At first when reading this: https://camo.githubusercontent.com/f16e12e98f8f8c5d79e7318bff1889b2c78363b9/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f656c61737469636265616e7374616c6b2d75732d656173742d312d3136373631313735323837342f64657461696c65642d776f726b666c6f772e706e67 , i thought it defined the number of tokens that a challenger need to challenge the application. Correct me if i misunderstand

**Comment by kangarang** [comment]
yes, the applicant's "staking deposit" is equivalent to the `minDeposit` because that's the only amount that's actually at risk. in the [code](https://github.com/skmgoldin/tcr/blob/master/contracts/Registry.sol#L33), it's actually termed `unstakedDeposit` because of this reason.

**Comment by hailq** [comment]
so the motivation of applicants to put the "deposit token" high when starting a new one is to avoid the "touch-and-removed" edge case ?

**Comment by kangarang** [comment]
yup, exactly
