### ISSUE TITLE
Update status of unchallenged application

### ISSUE THREAD

**Issue by hailq** [kangarang/tcr-ui#95]
According to this document https://github.com/skmgoldin/tcr/blob/master/owners_manual.md#commitreveal-voting . If there is no challenge, the applicant can update status to put the application into the registry. However, i tried but not only the applicant, everyone can update the status, also the application is removed all the time instead of putting into the registry.

**Comment by kangarang** [comment]
although the docs say applicant, yes, anyone can invoke `updateStatus`. 

> also the application is removed all the time instead of putting into the registry.

could you provide some code or logs to help me reproduce this please?
